### ISSUE TITLE
Minor issue checklist

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/collaborative-lesson-development#40]
- [x] Line 21 - the authors should distinguish the academic setting from the academic teaching setting, since the academic setting does very well in open source software development.
- [x] Lines 24-27 seem to be a personal statement against the academic system.
- [x] It would be useful to provide the URL in the text for rule #3 since online best practices for lesson development circles back to online collaborative lesson development.
- [x] line 141 - question their 'own' authority
- [x] In Rule #5, it would be helpful if the authors redirected to Rule #6 when discussing recognizing contributions.
- [x] Line 251, sustainable lessons 'in all domains'
- [x] Acknowledgements usually go at the end, not before the 10 rules?
- [x] pg 2, line 50: who -> whom
- [x] pg 2, line 53: which -> that
- [x] pg 3, line 77: has -> have
- [x] pg 3, line 78: I'd say 'formal training' here. There are many ways to learn to do something. Without this adjustment you risk coming off as dismissive or even derogatory towards faculty, which I don't think is your intent.
- [x] pg 4, line 117: I'd also revise this bit about programmers 'looking down' on Google Docs and the like. It contributes to the notion that programmers think they are better than others, which is not something that belongs in a manuscript about inclusive lesson development. Recent versions of Google Docs also allow for 'suggesting' mode edits, which could be considered a version of 'pre-merge review', in that the changes can be discussed, accepted, or rejected after they are initially made/proposed.
- [x] pg 5, line 168: look -> looks
- [x] pg 5, line 168: it has -> they have

**Comment by ianmilligan1** [comment]
I will take this on, using minor-issues branch.

**Comment by ianmilligan1** [comment]
Continued in #46 – for review and thoughts on two tweaks that I wasn't 100% sure on.
